darknet_ros_topic: /ns0/darknet_ros/bounding_boxes
output_bbx3d_topic: /ns0/darknet_ros_3d/bounding_boxes
output_markers_topic: /ns0/darknet_ros_3d/markers
point_cloud_topic: /ns0/camera/depth_registered/points
working_frame: world
mininum_detection_thereshold: 0.3
minimum_probability: 0.3
interested_classes: ["person", "water", "bottle"]
